apiVersion: v1
kind: Service
metadata:
  name: {{ include "zero-to-kanban.fullname" . }}-auth
  labels:
    {{- include "zero-to-kanban.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "zero-to-kanban.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: auth
  ports:
    - name: http
      port: 4000
      targetPort: {{ .Values.auth.containerPort }}
