#!/usr/bin/env bash
# Run the GitNexus CLI (https://github.com/abhigyanpatwari/GitNexus) from its
# pinned container image against this repo -- no local install needed.
#
#   .github/scripts/gitnexus.sh api-links   re-index, then regenerate docs/gitnexus/api-links.md
#   .github/scripts/gitnexus.sh <args...>   any gitnexus command: analyze, check --cycles, ...
#
# Used by the `gitnexus` job in .github/workflows/ci.yml and by the `just
# gitnexus*` recipes. Analyze options live in /.gitnexusrc. The index is written
# to .gitnexus/ (git-ignored by GitNexus itself); the registry of indexed repos
# goes to $GITNEXUS_HOME_DIR, default ~/.gitnexus so a GitNexus MCP server on
# the host sees the index too.
set -euo pipefail

# Pinned by digest. An index is only readable by a GitNexus of the same storage
# version: bump this together with the MCP server you run locally.
IMAGE="ghcr.io/abhigyanpatwari/gitnexus:1.6.12@sha256:7c9d62db60ce0b3ecccc1143b1866f3d5f67d8e594cc9b305e733a0a53a76469"

root="$(git rev-parse --show-toplevel)"
home_dir="${GITNEXUS_HOME_DIR:-$HOME/.gitnexus}"
mkdir -p "$home_dir"

tool="${CONTAINER_TOOL:-$(command -v podman >/dev/null && echo podman || echo docker)}"
# Run as the calling user so .gitnexus/ stays owned by them; rootless Podman
# additionally needs keep-id for that uid to map back to the host user.
user_args=(--user "$(id -u):$(id -g)")
if [ "$tool" = podman ]; then
  user_args=(--userns=keep-id "${user_args[@]}")
fi

# The repo is mounted at its host path so the paths GitNexus records in the
# registry are valid on the host as well.
gitnexus() {
  "$tool" run --rm "${user_args[@]}" \
    -v "$root:$root" -w "$root" \
    -v "$home_dir:/data/gitnexus" \
    -e GIT_CONFIG_COUNT=1 -e GIT_CONFIG_KEY_0=safe.directory -e GIT_CONFIG_VALUE_0="$root" \
    "$IMAGE" gitnexus "$@"
}

# One row per route URL. GitNexus links a consumer to a URL, not to a verb, so
# the consumers apply to every method listed on the row.
API_LINKS_QUERY="
MATCH (r:Route)
OPTIONAL MATCH (c)-[:CodeRelation {type: 'FETCHES'}]->(r)
WITH r.name AS route, r.filePath AS handler, r.method AS method, c.filePath AS consumer
WITH route, handler,
     list_sort(collect(DISTINCT method)) AS methods,
     list_sort(collect(DISTINCT consumer)) AS consumers
RETURN route, handler, methods, consumers
ORDER BY handler, route"

api_links() {
  local out="$root/docs/gitnexus/api-links.md" table
  gitnexus analyze >&2
  # ["GET","POST"] -> GET, POST
  table="$(gitnexus cypher "$API_LINKS_QUERY" \
    | jq -er .markdown \
    | sed -e 's/\["//g' -e 's/"\]//g' -e 's/","/, /g')"
  mkdir -p "$(dirname "$out")"
  cat > "$out" <<EOF
# API links

<!-- Generated by .github/scripts/gitnexus.sh api-links -- do not edit by hand. -->

Every HTTP route GitNexus found, and the files that call it. CI fails when this
file is out of date: regenerate it with \`just gitnexus-docs-generate\` and commit it.

A frontend call only shows up here when it goes through \`apiClient\` with a
literal path and no type argument (see \`frontend/src/services/apiClient.ts\`).
A route with no consumer is either unused or called in a way GitNexus cannot
see. Consumers are matched by URL, so they apply to every method on the row.

$table
EOF
  echo "wrote ${out#"$root"/}" >&2
}

case "${1:-}" in
  api-links) api_links ;;
  "") echo "usage: $0 api-links | <gitnexus args...>" >&2; exit 2 ;;
  *) gitnexus "$@" ;;
esac
